# Generated by fusen: do not edit by hand


#' Hello
#'
#' @param MyMessage String corresponding to the message to display
#'
#' @return a Message
#' @export
#'
#' @examples
#' Hello()
#' Hello(MyMessage = 'Bonjour')
#' 
Hello <- function(MyMessage = 'Hello') {
  message(MyMessage)
}
